name: Deploy React App
on:
  push:
jobs:
    Explore-Github-Action:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
            host: ${{ 87.236.19.5 }}
            username: ${{ kadiza3f }}
            password: ${{ XVhx5ME9 }}
            script: |
                cd /var/www/html
                git pull origin main